-- Baseline catalog schema. Flexible enough to "sell anything":
--   product_type spans physical | digital | service | subscription | rental,
--   and the JSONB `attributes` column holds arbitrary per-product fields with
--   no migration needed to add a new product kind.
-- IF NOT EXISTS throughout so it is safe on both fresh and existing databases.

CREATE TABLE IF NOT EXISTS products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    product_type  VARCHAR(32)  NOT NULL
                  CHECK (product_type IN ('PHYSICAL','DIGITAL','SERVICE','SUBSCRIPTION','RENTAL')),
    category      VARCHAR(255),
    base_price    NUMERIC(12,2) NOT NULL,
    currency      VARCHAR(3)   NOT NULL DEFAULT 'INR',
    image_url     VARCHAR(1024),
    attributes    JSONB        NOT NULL DEFAULT '{}'::jsonb,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_products_sku       ON products (sku);
CREATE INDEX        IF NOT EXISTS idx_products_category ON products (category);
CREATE INDEX        IF NOT EXISTS idx_products_type     ON products (product_type);
CREATE INDEX        IF NOT EXISTS idx_products_active   ON products (active);

CREATE TABLE IF NOT EXISTS variants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    sku         VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    price_delta NUMERIC(12,2) NOT NULL DEFAULT 0,
    attributes  JSONB        NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_variants_sku        ON variants (sku);
CREATE INDEX        IF NOT EXISTS idx_variants_product   ON variants (product_id);
