-- Launch-interest ("🔔 Notify me") signups captured from the storefront teaser/carousel. The storefront
-- still writes localStorage as an offline fallback, but this table is the source of truth the founder
-- reads via GET /api/catalog/admin/notify. One row per (topic, phone) — the unique index backs the
-- service-level idempotency so a re-submit is a no-op. Public write endpoint, so columns are bounded;
-- VARCHAR(32) covers the longest topic key ('delivery'), phone holds the normalized 10-digit form.
-- Idempotent DDL (IF NOT EXISTS), consistent with the rest of the migration set.

CREATE TABLE IF NOT EXISTS notify_signups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic       VARCHAR(32)  NOT NULL,
    phone       VARCHAR(20)  NOT NULL,
    email       VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_notify_topic_phone ON notify_signups (topic, phone);
