-- Inventory with two-phase reservations so checkout can HOLD stock, then either
-- COMMIT (sale completed) or RELEASE (payment failed / order cancelled).
-- Reservations are keyed by a unique order_id, which is what makes reserve/commit/
-- release idempotent under saga retries.

CREATE TABLE IF NOT EXISTS stock_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           VARCHAR(255) NOT NULL,
    available_qty INTEGER      NOT NULL DEFAULT 0 CHECK (available_qty >= 0),
    reserved_qty  INTEGER      NOT NULL DEFAULT 0 CHECK (reserved_qty >= 0),
    version       BIGINT       NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ  NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_stock_items_sku ON stock_items (sku);

CREATE TABLE IF NOT EXISTS reservations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   VARCHAR(255) NOT NULL,
    status     VARCHAR(16)  NOT NULL
               CHECK (status IN ('HELD','COMMITTED','RELEASED')),
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reservations_order_id ON reservations (order_id);

CREATE TABLE IF NOT EXISTS reservation_lines (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT  NOT NULL REFERENCES reservations (id) ON DELETE CASCADE,
    sku            VARCHAR(255) NOT NULL,
    qty            INTEGER NOT NULL CHECK (qty > 0)
);

CREATE INDEX IF NOT EXISTS idx_reservation_lines_res ON reservation_lines (reservation_id);
