-- Orders. order_id is the business id (a UUID) shared with inventory & payment as the saga key.
-- idempotency_key is the client-supplied Idempotency-Key header: UNIQUE so a retried checkout
-- returns the same order instead of creating/charging twice.
CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         VARCHAR(64)  NOT NULL UNIQUE,
    user_id          VARCHAR(128) NOT NULL,
    idempotency_key  VARCHAR(128) NOT NULL UNIQUE,
    status           VARCHAR(16)  NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'FAILED')),
    total_amount     NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    currency         VARCHAR(3)   NOT NULL DEFAULT 'INR',
    failure_reason   VARCHAR(512),
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id  BIGINT NOT NULL,
    sku         VARCHAR(64) NOT NULL,
    name        VARCHAR(512) NOT NULL,
    unit_price  NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    quantity    INTEGER NOT NULL CHECK (quantity > 0)
);

CREATE INDEX idx_order_items_order ON order_items (order_id);

-- Transactional outbox: written in the SAME transaction as the order, so an order can never
-- exist without its "needs processing" signal (and vice-versa). A scheduled poller drains
-- PENDING rows and drives the reserve -> pay -> commit/release saga. attempts caps retries.
CREATE TABLE order_outbox (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id  VARCHAR(64) NOT NULL,
    event_type    VARCHAR(64) NOT NULL,
    payload       JSONB NOT NULL DEFAULT '{}',
    status        VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED')),
    attempts      INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL,
    processed_at  TIMESTAMPTZ
);

CREATE INDEX idx_outbox_status ON order_outbox (status, id);
