-- Payments. One row per order (order_id UNIQUE) so a charge is idempotent: a retry for the
-- same order returns the existing payment instead of charging twice.
CREATE TABLE payments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       VARCHAR(64)  NOT NULL UNIQUE,
    amount         NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    currency       VARCHAR(3)   NOT NULL DEFAULT 'INR',
    status         VARCHAR(16)  NOT NULL CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    provider       VARCHAR(32)  NOT NULL,
    provider_ref   VARCHAR(128),
    failure_reason VARCHAR(512),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_payments_status ON payments (status);
