-- Records that a logged-in customer completed the Tally interest form and is therefore allowed to
-- request a call grant. One row per user (idempotent upsert keyed on user_id). The 5-hour cooldown
-- lives in Redis, NOT here — this table is only the eligibility gate.
CREATE TABLE videocall_eligibility (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(64)  NOT NULL UNIQUE,
    email       VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_videocall_eligibility_created_at ON videocall_eligibility (created_at);
