#!/bin/bash
# Generates a local .env with strong, random secrets for the stack (Phase 3, Pillar 2).
#
# Why this exists: no usable secret is checked into git. docker-compose.yml references every secret
# as ${VAR:?...} (required), so `docker compose up` fails closed until a .env supplies real values.
# This script creates that .env once, with cryptographically-random values, so dev is still one
# command. .env is gitignored and must never be committed.
#
# Usage:
#   ./scripts/gen-secrets.sh            # create .env if absent (no-op if it already exists)
#   ./scripts/gen-secrets.sh --force    # overwrite an existing .env (rotates every secret)
#
# Re-running with --force rotates secrets; you'll need `docker compose up -d --force-recreate` and
# (because JWT_SECRET changes) all existing tokens become invalid — users re-authenticate.
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root
ENV_FILE=".env"
FORCE="${1:-}"

if [[ -f "$ENV_FILE" && "$FORCE" != "--force" ]]; then
  echo "$ENV_FILE already exists — leaving it untouched. Use --force to rotate all secrets."
  exit 0
fi

# 32 random bytes, base64 → 44 chars, comfortably over the 32-byte HS256 minimum.
rand() { openssl rand -base64 32 | tr -d '\n'; }
# Shorter token for human-typed-ish creds (alphanumeric, no shell-special chars).
rand_alnum() { openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 24; }

cat > "$ENV_FILE" <<EOF
# Generated by scripts/gen-secrets.sh — DO NOT COMMIT (this file is gitignored).
# Re-run with --force to rotate every secret.

# Postgres password (shared by all services in dev).
DB_PASSWORD=$(rand_alnum)

# JWT signing key (HS256, >= 32 bytes). Rotating this invalidates all issued tokens.
JWT_SECRET=$(rand)

# MinIO (S3-compatible object storage) root credentials.
MINIO_ROOT_USER=$(rand_alnum)
MINIO_ROOT_PASSWORD=$(rand_alnum)

# Grafana admin password (user defaults to 'admin').
GRAFANA_PASSWORD=$(rand_alnum)

# Password for the gateway's dev self-signed TLS keystore (Pillar 4). Used at image build AND runtime.
TLS_KEYSTORE_PASSWORD=$(rand_alnum)

# --- Non-secret knobs (safe defaults live in docker-compose.yml; override here if needed) ---
# Google OAuth2 (optional locally — guest tokens cover the full journey). Fill to enable Google login.
GOOGLE_CLIENT_ID=dummy-client-id
GOOGLE_CLIENT_SECRET=dummy-client-secret
# RBAC: comma-separated emails promoted to ADMIN at login (empty → no admins). Admins use Google login.
ADMIN_EMAILS=
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE with fresh random secrets (mode 600). It is gitignored — never commit it."
echo "Next: docker compose up -d --build"
